name: product_viewer
description: "Simple product viewer project utilizing fakestoreapi.com"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2
  flutter: ">=3.24.0"

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  build_runner: ^2.4.12
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  gap: ^3.0.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  logger: ^2.4.0
  skeletonizer: ^1.4.2
  transparent_image: ^2.0.1


dev_dependencies:
  auto_route_generator: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/